name: Azure Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/deployAzureInfrastructure.yml'
  pull_request:

env:
  AZURE_SUBSCRIPTION_ID: '558bd446-4212-46a2-908c-9ab0a628705e'
  AZURE_RESOURCE_GROUP_NAME_MLFLOW: mlflow-rg
  AZURE_LOCATION: westeurope

jobs:
  validation:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy vnet - validation
    - name: Deploy vnet - validation
      id: vnet_validation
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/VirtualNetwork/deploy.vnet.json
        parameters: ${{ github.workspace }}/infra/VirtualNetwork/params.vnet.json
        deploymentMode: validate
    
    # Deploy Key Vault - validation
    - name: Deploy Key Vault - validation
      id: key_vault_validation
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/KeyVault/deploy.keyVault.json
        parameters: ${{ github.workspace }}/infra/KeyVault/params.keyVault.json
        deploymentMode: validate
    
    # Deploy Storage - validation
    - name: Deploy Storage - validation
      id: storage_validation
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/Storage/deploy.storage.json
        parameters: ${{ github.workspace }}/infra/Storage/params.storage.json
        deploymentMode: validate
    
    # Deploy Container Registry - validation
    - name: Deploy Container Registry - validation
      id: container_registry_validation
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/ContainerRegistry/deploy.containerRegistry.json
        parameters: ${{ github.workspace }}/infra/ContainerRegistry/params.containerRegistry.json
        deploymentMode: validate
    
    # # Deploy App Service - validation
    # - name: Deploy App Service - validation
    #   id: app_service_validation
    #   uses: azure/arm-deploy@v1
    #   with:
    #     scope: resourcegroup
    #     subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
    #     resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
    #     region: ${{ env.AZURE_LOCATION }}
    #     template: ${{ github.workspace }}/infra/AppService/deploy.appService.json
    #     parameters: ${{ github.workspace }}/infra/AppService/params.appService.json
    #     deploymentMode: validate
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout

  deployment:
    needs: [ validation ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy vnet
    - name: Deploy vnet
      id: vnet_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/VirtualNetwork/deploy.vnet.json
        parameters: ${{ github.workspace }}/infra/VirtualNetwork/params.vnet.json
        deploymentMode: Incremental
    
    # Deploy Key Vault
    - name: Deploy Key Vault
      id: key_vault_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/KeyVault/deploy.keyVault.json
        parameters: ${{ github.workspace }}/infra/KeyVault/params.keyVault.json
        deploymentMode: Incremental
    
    # Deploy Storage
    - name: Deploy Storage
      id: storage_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/Storage/deploy.storage.json
        parameters: ${{ github.workspace }}/infra/Storage/params.storage.json
        deploymentMode: Incremental
    
    # Deploy Container Registry
    - name: Deploy Container Registry
      id: container_registry_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/ContainerRegistry/deploy.containerRegistry.json
        parameters: ${{ github.workspace }}/infra/ContainerRegistry/params.containerRegistry.json
        deploymentMode: Incremental
    
    # # Deploy App Service
    # - name: Deploy App Service
    #   id: app_service_deployment
    #   uses: azure/arm-deploy@v1
    #   with:
    #     scope: resourcegroup
    #     subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
    #     resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_MLFLOW }}
    #     region: ${{ env.AZURE_LOCATION }}
    #     template: ${{ github.workspace }}/infra/AppService/deploy.appService.json
    #     parameters: ${{ github.workspace }}/infra/AppService/params.appService.json
    #     deploymentMode: Incremental
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout
